# build script for dedis/cothority libraries
go:
    - 1.5.1
env:
    global:
        - REPO="dedis/cothority"
        - HOME="/home/travis"
        - GOPATH="$HOME"
        - PATH="$HOME/bin:$PATH"
before_install:
    - mkdir -p $HOME/src/github.com/dedis
    - mkdir -p $HOME/bin
    - ls $TRAVIS_BUILD_DIR
    - mv $TRAVIS_BUILD_DIR $HOME/src/github.com/dedis
    - cd $HOME/src/github.com/dedis/cothority
    - go list -f '{{join .Deps "\n"}} {{join .TestImports "\n"}}' ./... | grep -v "^github.com/dedis/cothority" | xargs go get -t -v
before_script:
    - git remote add production https://github.com/DeDiS/cothority.git
    - git fetch -a production
script:
    - go run dedis-travis-script.go
